import type { paths as MarketPaths } from "../../core/generated/market.types"

export const CATEGORY_OP = {
	steam: 'Category.Steam',
	telegram: 'Category.Telegram',
	fortnite: 'Category.Fortnite',
	mihoyo: 'Category.Mihoyo',
	riot: 'Category.Riot',
	supercell: 'Category.Supercell',
	ea: 'Category.EA',
	wot: 'Category.Wot',
	wotBlitz: 'Category.WotBlitz',
	gifts: 'Category.Gifts',
	epicGames: 'Category.EpicGames',
	escapeFromTarkov: 'Category.EscapeFromTarkov',
	socialClub: 'Category.SocialClub',
	uplay: 'Category.Uplay',
	discord: 'Category.Discord',
	tiktok: 'Category.TikTok',
	instagram: 'Category.Instagram',
	battleNet: 'Category.BattleNet',
	chatgpt: 'Category.ChatGPT',
	vpn: 'Category.Vpn',
	roblox: 'Category.Roblox',
	warface: 'Category.Warface',
	minecraft: 'Category.Minecraft',
	hytale: 'Category.Hytale',
} as const

export const CATEGORY_PATH = {
	steam: '/steam',
	telegram: '/telegram',
	fortnite: '/fortnite',
	mihoyo: '/mihoyo',
	riot: '/riot',
	supercell: '/supercell',
	ea: '/ea',
	wot: '/world-of-tanks',
	wotBlitz: '/wot-blitz',
	gifts: '/gifts',
	epicGames: '/epicgames',
	escapeFromTarkov: '/escape-from-tarkov',
	socialClub: '/socialclub',
	uplay: '/uplay',
	discord: '/discord',
	tiktok: '/tiktok',
	instagram: '/instagram',
	battleNet: '/battlenet',
	chatgpt: '/chatgpt',
	vpn: '/vpn',
	roblox: '/roblox',
	warface: '/warface',
	minecraft: '/minecraft',
	hytale: '/hytale',
} as const satisfies Record<string, keyof MarketPaths>
